# This workflow will run regression tests using node and docker

name: Regression Tester

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  build: 
    name: regression
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: installer
        run: npm install

      - name: Copy Environment
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BASE_URL: "http://automationpractice.com"
          envkey_SELENIUM: "selenium/standalone-chrome"
          file_name: .env

      - name: regression
        run: npm run regression
